function setPlanet(PlanetName)
	{
	  document.getElementById("PName").value = PlanetName;
	  checkPlanet();
	}
   
    function checkPlanet()
	{
	  var arrNames = ["lewis hamilton", "giuseppe farina", "juan manuel fangio" ,
       "niki lauda",  "nelson piquet",  "alain prost", "ayrton senna", "micheal schumacher",
        "kimi raikkonen", "sebastian vettel", "nico roseberg", "fernando alonso", "max verstappen",
        "charles leclerc", "sergio perez", "george russell", "carlos sainz", "lando norris",  "valtteri bottas",
        "daniel ricciardo", "lance stroll", "mick schumacher","yuki tsunoda", 
        "zhou guanyu", "alexander albon", "nyck de vries"];


	  var arrCountry = ["United Kingdom" , "Italy", "Argentina", 
        "Austria", "Brazil",  "France", "Brazil", "Germany",
        "Finland", "Germany", "Germany", "Spain", "Netherlands",  
        "Monaco", "Mexico" , "United Kingdom", "Spain", "United Kingdom", "Finland",
        "Australia", "Canada", "Germany", "Japan" ,
        "China", "Thailand", "Netherlands"];
	  
      
      var arrInfo = ["Sir Lewis Carl Davidson Hamilton MBE HonFREng (born 7 January 1985) is a British racing driver currently competing in Formula One for Mercedes. In Formula One, Hamilton has won a joint-record seven World Drivers' Championship titles (tied with Michael Schumacher) and holds the records for the most wins (103), pole positions (103), and podium finishes (191), among others. Hamilton joined the McLaren young driver programme in 1998. This led to a Formula One drive with McLaren from 2007 to 2012, making Hamilton the first, and so far only, black driver to race in the series. In his inaugural season, Hamilton set numerous records as he finished runner-up to Kimi Räikkönen by one point. The following season, he won his maiden title in dramatic fashion—making a crucial overtake on the last lap of the last race of the season—to become the then-youngest Formula One World Champion in history. After six years with McLaren, Hamilton signed with Mercedes in 2013. Changes to the regulations for 2014 mandating the use of turbo-hybrid engines saw the start of a highly successful period for Hamilton, during which he has won six further drivers' titles. Consecutive titles came in 2014 and 2015 during an intense rivalry with teammate Nico Rosberg. Following Rosberg's retirement, Ferrari's Sebastian Vettel became Hamilton's closest rival in two championship battles, in which Hamilton twice overturned mid-season point deficits to claim consecutive titles again in 2017 and 2018. His third and fourth consecutive titles followed in 2019 and 2020 to equal Schumacher's record of seven drivers' titles.",
        "Emilio Giuseppe Farina, also known as Giuseppe Antonio Nino Farina,[3] (Italian pronunciation: [dʒuˈzɛppe ˈniːno faˈriːna]; 30 October 1906 – 30 June 1966) was an Italian racing driver and first official Formula One World Champion. He gained the title in 1950. He was the Italian Champion in 1937, 1938 and 1939.",
        "Juan Manuel Fangio born on 24 June 1911 – 17 July 1995, nicknamed El Chueco (the bowlegged or bandy legged one) or El Maestro (The Master or The Teacher), was an Argentine racing car driver. He dominated the first decade of Formula One racing, winning the World Drivers' Championship five times.",
        "Andreas Nikolaus 'Niki' Lauda (22 February 1949 – 20 May 2019) was an Austrian Formula One driver and aviation entrepreneur. He was a three-time F1 World Drivers' Champion, winning in 1975, 1977 and 1984, and is the only driver in F1 history to have been champion for both Ferrari and McLaren, two of the sport's most successful constructors. Lauda emerged as Formula One's star driver amid a 1975 title win and leading the 1976 championship battle. Lauda was seriously injured in a crash at the 1976 German Grand Prix while racing at the Nürburgring; during the crash his Ferrari 312T2 burst into flames nearly resulting in his death after inhaling hot toxic fumes and suffering severe burns. He survived and recovered sufficiently to race again just six weeks later at the Italian Grand Prix. Although he lost that year's title by just one point to James Hunt, he won his second championship the year after, during his final season at Ferrari. After a couple of years at Brabham and two years' hiatus, Lauda returned and raced four seasons for McLaren between 1982 and 1985, during which he won the 1984 title by half a point over his teammate Alain Prost.",
        "Nelson Piquet Souto Maior is a Brazilian retired racing driver and businessman. Since his retirement, Piquet, a three-time World Champion, has been ranked among the greatest Formula One (F1) drivers in various motorsport polls. With advice from Emerson Fittipaldi, Piquet went to Europe to further success by taking the record number of wins in Formula Three in 1978, beating Jackie Stewart's all-time record. In the same year, he made his Formula One debut with the Ensign team and drove for McLaren and Brabham. In 1979, Piquet moved to the Brabham team and finished the runner-up in 1980 before winning the championship in 1981. Piquet in 1982 was hampered by severe engine unreliability, but he saw a resurgence for 1983 and his second world championship. He moved to the Williams team in 1986 and was a title contender until the final round in Australia. Piquet took his third and final championship in 1987 during a heated battle with teammate Nigel Mansell which left the pair's relationship sour.", 
        "Alain Marie Pascal Prost born 24 February 1955 is a French retired racing driver and Formula One team owner. A four-time Formula One World Drivers' Champion, from 1987 until 2001 he held the record for most Grand Prix victories until Michael Schumacher surpassed Prost's total of 51 victories at the 2001 Belgian Grand Prix. During the 1980s and early 1990s Prost formed a fierce sporting rivalry, mainly with Ayrton Senna but also Nelson Piquet and Nigel Mansell. In 1986, at Adelaide in the last race of the season, he beat Mansell and Piquet of Williams to the title, after Mansell retired late in the race and Piquet was pulled in for a late precautionary pit stop. Senna joined Prost at McLaren in 1988 and the two had a series of controversial clashes, including a collision at the 1989 Japanese Grand Prix that gave Prost his third Drivers' Championship. A year later at the same venue they collided again, but this time Prost, driving for Ferrari, lost out. Before the end of a winless 1991 season Prost was fired by Ferrari for his public criticism of the team. After a sabbatical in 1992, he joined the Williams team, prompting Mansell, the reigning Drivers' Champion, to leave for CART. With a competitive car, Prost won the 1993 championship and retired from Formula One driving at the end of the year.",
        "Ayrton Senna da Silva (21 March 1960 – 1 May 1994) was a Brazilian racing driver who won the Formula One World Drivers' Championship in 1988, 1990, and 1991. Senna is one of three Formula One drivers from Brazil to win the World Championship and won 41 Grands Prix and 65 pole positions, with the latter being the record until 2006. He died in an accident while leading the 1994 San Marino Grand Prix, driving for the Williams team. He made his Formula One debut with Toleman-Hart in 1984, before moving to Lotus-Renault the following year and winning six Grands Prix over the next three seasons. In 1988, he joined Frenchman Alain Prost at McLaren-Honda. Between them, they won all but one of the 16 Grands Prix that year, and Senna claimed his first World Championship. Senna claimed his second and third championships in 1990 and 1991. In 1992, the Williams-Renault combination began to dominate Formula One. Senna nonetheless managed to finish the 1993 season as runner-up, winning five races and negotiating a move to Williams in 1994. Senna was recognised for his qualifying speed over one lap, and from 1989 until 2006 he held the record for most pole positions.",
        "Michael Schumacher born 3 January 1969 is a German former racing driver who competed in Formula One for Jordan, Benetton, Ferrari, and Mercedes. Schumacher has a joint-record seven World Drivers' Championship titles (tied with Lewis Hamilton) and, at the time of his retirement from the sport in 2012, he held the records for the most wins (91), pole positions (68), and podium finishes (155)—which have since been broken by Hamilton—while he maintains the record for the most fastest laps (77), among others. After a one-off Formula One appearance with Jordan at the 1991 Belgian Grand Prix, Schumacher was signed by Benetton for the rest of the 1991 season. He won his first and second drivers' titles consecutively in 1994 and 1995. Schumacher moved to the struggling Ferrari team in 1996. During his first years at the team, Schumacher lost out on the title in the final race of the season in 1997 and 1998 and suffered a broken leg from a brake failure in 1999. He and Ferrari won five consecutive titles from 2000 to 2004, including unprecedented sixth and seventh titles, breaking several records. After finishing third in 2005 and second in 2006, Schumacher retired from the sport, although he later made a brief return with Mercedes from 2010 to 2012. In December 2013, Schumacher suffered a severe brain injury in a skiing accident. He was placed in a medically induced coma until June 2014. He left the hospital in Grenoble for further rehabilitation at the Lausanne University Hospital, before being relocated to his home to receive medical treatment and rehabilitation privately in September 2014.",
        "Kimi-Matias Räikkönen born 17 October 1979, nicknamed The Iceman, is a Finnish racing driver who competed in Formula One between 2001 and 2021 for Sauber, McLaren, Ferrari, Lotus, and Alfa Romeo. Räikkönen won the 2007 Formula One World Championship while driving for Ferrari; he also managed to finish second overall twice and third three times. Räikkönen is the most successful Finnish Formula One driver by several metrics and has the fifth-most podium finishes (103), third-most fastest laps (46), and second-most race starts (349) in Formula One history. He is known for his reserved personality and reluctance to participate in public relations.",
        "Sebastian Vettel born 3 July 1987 is a German racing driver who competed in Formula One from 2007 to 2022 for BMW Sauber, Toro Rosso, Red Bull, Ferrari, and Aston Martin. Vettel is one of the most successful drivers in Formula One history and has won four World Drivers' Championship titles, which he won consecutively from 2010 to 2013. Vettel holds the record for being the youngest World Champion in Formula One. He also has the third-most race victories (53) and podium finishes (122), and fourth-most pole positions (57).Vettel started his Formula One career as a test driver for BMW Sauber in 2006, making a one-off racing appearance in 2007. As part of the Red Bull Junior Team, Vettel appeared for Toro Rosso later that year and was kept as a full-time driver for 2008. Vettel was promoted to Red Bull in 2009. With Red Bull, Vettel won four consecutive titles from 2010 to 2013, the first of which made him the sport's youngest World Champion. In 2013, he set the record for the most consecutive race wins with nine. Vettel signed for Ferrari for 2015 replacing Fernando Alonso and became Mercedes' and Lewis Hamilton's closest challenger in two title fights in 2017 and 2018, although he finished both years as runner-up. He parted ways with Ferrari at the end of the 2020 season to race with Aston Martin for the 2021 and 2022 seasons, before retiring from Formula One at the end of the 2022 season.",
        "Nico Erik Rosberg (born 27 June 1985) is a German-Finnish former professional racing driver. He competed in Formula One from 2006 to 2016, winning the World Drivers' Championship in 2016 with Mercedes-AMG Petronas Motorsport. The only child of Finnish 1982 Formula One World Champion Keke Rosberg. Rosberg first drove in Formula One with Williams from 2006 to 2009 and achieved two podium finishes for the team in 2008. For 2010, he moved to Mercedes, partnering fellow German and seven-time world champion Michael Schumacher. Rosberg took his first career win at the 2012 Chinese Grand Prix. He was the teammate of former karting friend and eventual seven-time World Drivers' Champion, Lewis Hamilton, from 2013 to 2016, twice finishing runner-up to his teammate before a title win in 2016. Rosberg announced his retirement from motor racing five days after clinching the title, citing wanting to spend more time with his family. Overall he competed in 206 Grands Prix, winning 23, securing 57 podium finishes, 30 pole positions, and amassing 1594.5 championship points.",
        "Fernando Alonso Díaz (born 29 July 1981) is a Spanish racing driver currently competing for Alpine in Formula One. He won the series' World Drivers' Championship in 2005 and 2006 with Renault, and has also driven for McLaren, Ferrari, and Minardi. With Toyota, Alonso won the 24 Hours of Le Mans twice, in 2018 and 2019, and the FIA World Endurance Championship in 2018–19. He also won the 24 Hours of Daytona with Wayne Taylor Racing in 2019. He debuted in Formula One with Minardi in 2001 before joining Renault as a test driver for 2002. Promoted to a race seat in 2003, Alonso won two drivers' championships in 2005 and 2006, becoming the youngest pole-sitter, youngest race winner, youngest world champion, and youngest two-time champion in the sport's history at the time. After finishing just one point behind eventual champion Kimi Räikkönen with McLaren in 2007, he returned to Renault for 2008 and 2009 and won two races in the former year for fifth overall. Alonso drove for Ferrari from 2010 to 2014, finishing runner-up to Sebastian Vettel in 2010, 2012, and 2013 with the title battles in 2010 and 2012 going down to the last race of the season. A second stint with McLaren from 2015 to 2018 resulted in no further success. After a two-year sabbatical, Alonso returned to Formula One in 2021 with Alpine. At the 2021 Qatar Grand Prix, Alonso scored his first podium in seven years. Alonso is due to move to Aston Martin for the 2023 season. At the 2022 Singapore Grand Prix, he broke the record for most starts in Formula One.",
        "Max Emilian Verstappen is a Belgian-Dutch racing driver and the 2021 and 2022 Formula One World Champion. He competes under the Dutch flag in Formula One with Red Bull Racing. At the 2015 Australian Grand Prix, when he was aged 17 years, 166 days, he became the youngest driver to compete in Formula One. After spending the 2015 season with Scuderia Toro Rosso, Verstappen started his 2016 campaign with the Italian team before being promoted to parent team Red Bull Racing after four races as a replacement for Daniil Kvyat. At the age of 18, he won the 2016 Spanish Grand Prix on his debut for Red Bull Racing, becoming the youngest-ever driver and the first Dutch driver to win a Formula One Grand Prix. After winning the 2021 Abu Dhabi Grand Prix, Verstappen became the first Dutch driver to win the Formula One World Championship, and the 34th Formula One World Drivers' Champion. He won his second consecutive Formula One championship the next season. As of the 2022 Abu Dhabi Grand Prix, Verstappen has achieved 35 victories and 20 pole positions. He scored the first hat-trick of his career at the 2021 French Grand Prix and his first grand slam at the 2021 Austrian Grand Prix. He scored his second grand slam at the 2022 Emilia Romagna Grand Prix.",
        "Charles Marc Hervé Perceval Leclerc (born 16 October 1997) is a Monégasque racing driver, currently racing in Formula One for Scuderia Ferrari. He won the GP3 Series championship in 2016 and the FIA Formula 2 Championship in 2017. Leclerc made his Formula One debut in 2018 for Sauber, a team affiliated with Ferrari, for which he was part of the Ferrari Driver Academy. With Sauber having finished last the year before, Leclerc led the charge to improve its finishing position in the constructors' championship to eighth and was the higher ranked of the two Sauber drivers. He joined Ferrari the next season and became the second-youngest driver to qualify on pole position in Formula One at the 2019 Bahrain Grand Prix. The 2019 season also saw Leclerc take his first career win in Belgium. He won the FIA Pole Trophy for most pole positions in the 2019 season, becoming the youngest driver to win it, before winning it again in 2022. As of the 2022 Abu Dhabi Grand Prix, Leclerc has achieved 5 race wins and 18 pole positions in Formula One. He scored the first grand slam of his career at the 2022 Australian Grand Prix.",
        "Sergio Michel Checo Pérez Mendoz (born 26 January 1990), is a Mexican racing driver who races in Formula One for Red Bull Racing, having previously driven for Sauber, McLaren, Force India, and Racing Point. He won his first Formula One Grand Prix at the 2020 Sakhir Grand Prix, breaking the record for the number of starts before a race win at 190. He also earned his first Formula One pole position at the 2022 Saudi Arabian Grand Prix, breaking the record for the most races before a first pole position at 215. Pérez was a member of the Ferrari Driver Academy until 2012. He made his Formula One debut driving for Sauber during the 2011 season. He took his first Formula One podium at the 2012 Malaysian Grand Prix with Sauber. Force India signed Pérez for the 2014 season with a €15 million contract. In December, Pérez signed with Red Bull Racing for the 2021 season. Pérez then won the 2021 Azerbaijan Grand Prix with the team and secured the second Formula 1 Grand Prix win of his career. Pérez scored his maiden Formula One pole position at the 2022 Saudi Arabian Grand Prix, with his third career win coming at the 2022 Monaco Grand Prix. Pérez scored his fourth win at the 2022 Singapore Grand Prix.",
        "George William Russell (born 15 February 1998) is a British racing driver currently competing in Formula One for Mercedes. He was the 2018 FIA Formula 2 champion and the 2017 GP3 Series champion, driving for ART in both campaigns. Following his Formula 2 championship win, Russell signed for Williams in 2019, making his debut at the 2019 Australian Grand Prix, although he stood in for Lewis Hamilton at Mercedes at the 2020 Sakhir Grand Prix. Russell achieved his first F1 podium with Williams at the 2021 Belgian Grand Prix. In 2022, Russell departed Williams to race for the Mercedes team, having been a member of the Mercedes Junior Driver Programme since 2017. Russell achieved his first F1 victory at the 2022 São Paulo Grand Prix.",
        "Carlos Sainz Vázquez de Castro (born 1 September 1994), otherwise known as Carlos Sainz Jr. or simply Carlos Sainz, is a Spanish racing driver currently competing in Formula One for Scuderia Ferrari. He is the son of Carlos Sainz Sr., a double World Rally Champion. In 2012, Sainz raced in the British and European Formula 3 championships for Carlin. He raced for DAMS in the 2014 Formula Renault 3.5 season, winning the championship before moving to F1 with Toro Rosso. Sainz moved to McLaren for the 2019 season, while at the same time ending his contract with Red Bull Racing. At the 2019 Brazilian Grand Prix Sainz took his maiden Formula One podium finish with third. Sainz moved to Ferrari at the end of the 2020 season. At the 2022 British Grand Prix, Sainz took his maiden Formula One pole position and career win.",
        "Lando Norris (born 13 November 1999) is a Belgian-British racing driver currently competing in Formula One with McLaren, racing under the British flag. He won the MSA Formula championship in 2015, and the Toyota Racing Series, Eurocup Formula Renault 2.0 and Formula Renault 2.0 Northern European Cup in 2016. He also received the McLaren Autosport BRDC Award that year. He subsequently joined the McLaren Young Driver Programme in 2017 and won the 2017 FIA Formula 3 European Championship, competing with Carlin Motorsport. Consequently, he was promoted to the Formula 2 Carlin team, where he finished second in 2018, competing with Carlin Motorsport. He was then announced as a McLaren driver in 2018, alongside Carlos Sainz Jr. He achieved his first podium in Formula One at the 2020 Austrian Grand Prix and his best finish is second in the 2021 Italian Grand Prix, finishing behind teammate Daniel Ricciardo.",
        "Valtteri Viktor Bottas  (born 28 August 1989) is a Finnish racing driver currently competing in Formula One for Alfa Romeo, having previously driven for Mercedes from 2017 to 2021 and Williams from 2013 to 2016. Bottas has scored 10 race wins and 67 podiums. He contributed to five constructors championship wins for Mercedes, and has been drivers' championship runner-up twice, in 2019 and 2020. In 2013, he joined Williams as a full time driver partnering Pastor Maldonado. He would remain at Williams until 2017, achieving a top championship position of fourth in 2014 and finishing on the podium nine times during his time with Williams. Following Nico Rosberg's decision to retire following the 2016 season, Bottas was signed by Mercedes as his replacement to partner Lewis Hamilton. During his time with Mercedes which would go on to last until 2022, Bottas finished in the top three of the championship four times and won 10 races in addition to 58 podiums. After five constructor championships won alongside Hamilton, Following Kimi Räikkönen's decision to retire following the 2021 season, Bottas was signed by Alfa Romeo as his replacement to partner Zhou Guanyu.",
        "Daniel Joseph Ricciardo AM (born 1 July 1989) is an Italian-Australian racing driver who last raced in Formula One driving for McLaren, under the Australian flag. He made his debut at the 2011 British Grand Prix with the HRT team as part of a deal with Red Bull Racing, for whom he was test driving under its sister team Scuderia Toro Rosso. He has achieved 8 Grand Prix victories in Formula One. He is 3rd driver for Red Bull Racing from 2023. Ricciardo joined Toro Rosso in 2012 full-time after the team changed its driver lineup and drove a Ferrari-powered car for them in 2012 and 2013. In 2014, Ricciardo was promoted to Red Bull as a replacement for the retired Mark Webber alongside multiple time world champion Sebastian Vettel. In his first season with Red Bull under Renault power, Ricciardo finished third in the championship with his first three Formula One wins, in Canada, Hungary, and Belgium. After two years without a victory, Ricciardo returned to the top of the podium at the 2016 Malaysian Grand Prix, eventually sealing third in the championship for the second time in three years at the 2016 Mexican Grand Prix. He has since added victories for Red Bull at the Azerbaijan Grand Prix in 2017 and the Chinese and Monaco Grands Prix in 2018. After 2018, Ricciardo signed with Renault and raced for them in the 2019 and 2020 seasons. He joined McLaren for the 2021 and 2022 Formula One seasons, alongside Lando Norris. He obtained his first race win with McLaren at the 2021 Italian Grand Prix.",
        "Lance Strulovitch (born 29 October 1998), better known as Lance Stroll, is a Canadian–Belgian racing driver competing under the Canadian flag in Formula One. He has driven for Aston Martin since 2021, having previously driven for Williams and Racing Point. He was Italian F4 champion in 2014, Toyota Racing Series champion in 2015, and 2016 FIA European Formula 3 champion. He was part of the Ferrari Driver Academy from 2010 to 2015. He achieved his first podium finish, a 3rd place, at the 2017 Azerbaijan Grand Prix, becoming the second-youngest driver to finish an F1 race on the podium and the youngest (and latest as of the end of 2021) to do so during his rookie season. At the 2020 Turkish Grand Prix, Stroll took his first pole position in Formula One. Stroll also competed in endurance racing, taking part in the 24 Hours of Daytona in 2016 and 2018.",
        "Mick Schumacher (born 22 March 1999) is a German racing driver who most recently competed for Haas in Formula One .Schumacher began his career in karting in 2008, progressing to the German ADAC Formula 4 by 2015. After winning the 2018 FIA F3 European Championship, he progressed to Formula 2 in 2019, and won the 2020 Formula 2 Championship. He is the son of seven-time Formula One World Champion Michael Schumacher. Schumacher improved his best qualifying position at the Canadian Grand Prix, starting sixth. He was running in seventh place until an engine failure ended his race. At the following race, the British Grand Prix, he started nineteenth and recovered to eighth to score his first Formula One points. A week later at the Austrian Grand Prix, Schumacher qualified seventh and finished sixth his best Formula One result, promoting him to fifteenth place in the drivers' championship at the halfway point of the 2022 season. He reached Q3 again at the Dutch Grand Prix but finished outside the points.",
        "Yuki Tsunoda (born 11 May 2000) is a Japanese racing driver who is racing for Scuderia AlphaTauri in Formula One. Supported by Honda since 2016 through the Honda Formula Dream Project, he was the 2018 Japanese F4 champion and in 2019 also received backing from Red Bull. He finished third in the 2020 Formula 2 Championship and made his Formula One debut in 2021 for AlphaTauri.",
        "Zhou Guanyu (born 30 May 1999) is a Chinese racing driver who currently competes in Formula One for Alfa Romeo. He is the first Chinese driver to compete in Formula One. He competed in the FIA Formula 2 Championship for UNI-Virtuosi Racing from 2019 to 2021, having finished 3rd in the 2021 campaign. A former member of the Alpine Academy, he served as the test driver for the Renault F1 Team and the Alpine F1 Team in 2020 and 2021 respectively. Prior to that, he was a member of the Ferrari Driver Academy from 2014 to 2018 and served as the development driver for Formula E team DS Techeetah in 2018.",
        "Alexander Albon Ansusinha (born 23 March 1996) is a Thai-British racing driver currently competing in Formula One for Williams Racing, under the Thai flag. Albon previously raced in Formula One for Scuderia Toro Rosso and Red Bull Racing and in DTM for AF Corse. After becoming part of the Red Bull Junior Team in 2012, he was promoted to open-wheel cars for the 2012 Eurocup Formula Renault 2.0 season. He spent three years in the series and finished third in the 2014 championship. He moved to the FIA Formula 3 European Championship in 2015, where he finished seventh. He signed with ART Grand Prix to contest the 2016 GP3 Series and ended the season as runner-up behind teammate Charles Leclerc. In 2017 Albon moved up to the FIA Formula 2 Championship with ART, where he finished his maiden year tenth in the standings. He then switched to the DAMS team for 2018, winning four races and finishing third in the championship. He made his Formula One début in 2019 with Toro Rosso alongside Daniil Kvyat. After twelve races, Albon was promoted to Red Bull Racing, partnering Max Verstappen and replacing Pierre Gasly. He took his first podium finish – and the first in a World Championship Formula One race for a Thai driver – at the 2020 Tuscan Grand Prix.",
        "Hendrik Johannes Nicasius Nyck de Vries (born 6 February 1995) is a Dutch racing driver who is currently serving as the reserve driver for the Mercedes-AMG Petronas F1 Team. He is confirmed to be driving full-time in Formula 1 at Scuderia AlphaTauri in 2023. He won the 2020–21 Formula E World Championship and the 2019 FIA Formula 2 Championship, as well as the 2010 and 2011 Karting World Championships. He was signed to the McLaren young driver programme from January 2010 until May 2019 and Audi Sport racing academy from October 2016 until August 2019. De Vries made his Formula One debut in September 2022 for Williams at the 2022 Italian Grand Prix. At the Italian Grand Prix, De Vries took part in first practice in place of Sebastian Vettel at Aston Martin. De Vries then replaced Alex Albon at Williams for third practice, qualifying, and the race, after Albon developed appendicitis and was ruled out on Saturday morning. He managed to advance to Q2 and qualify thirteenth, ahead of his Williams teammate Nicholas Latifi. He started eighth after penalties were applied to multiple drivers. He finished the race in ninth position, scoring points on his race debut and rewarded with Driver of the Day by fans."  
    ];


	  var arrImgs = ["../img/driver_img/Lewis_Hamilton.jpg", "../img/driver_img/NinoFarina.jpg", "../img/driver_img/Fangio.png", "../img/driver_img/Niki_Lauda.jpg",
        "../img/driver_img/Nelson_Piquet_Souto_Maior.jpg", "../img/driver_img/Alain_Prost.jpg" , "../img/driver_img/ayrton-senna.jpg", "../img/driver_img/Michael-Schumacher.jpg",
        "../img/driver_img/Kimi_Raikkonen.jpg", "../img/driver_img/Sebastian_Vettel.jpg", "../img/driver_img/Nico_Rosberg.jpg", "../img/driver_img/Alonso.jpg", 
        "../img/driver_img/Max_Verstappen.jpg", "../img/driver_img/Charles-Leclerc.jpg", "../img/driver_img/Sergio_Pérez.jpg", "../img/driver_img/George_Russell.jpg" ,
        "../img/driver_img/Carlos_Sainz.jpg", "../img/driver_img/Lando_Norris.jpg", "../img/driver_img/Valtteri_Bottas.jpg", "../img/driver_img/Dainel_Ricciardo.jpg", 
        "../img/driver_img/Lance_Stroll.jpg", "../img/driver_img/Mick_Schumacher.jpg", "../img/driver_img/Yuki_Tsunoda.jpg", "../img/driver_img/Zhou_Guanyu.jpg",
        "../img/driver_img/Alex_Albon.jpg", "../img/driver_img/nyck_de_vries.jpg"];

      
      
      var result, ndriverName, imgDriver;
	  
      ndriverName = document.getElementById("dName").value.toLowerCase();
	  
	  var index = -1;
	  
        for (var i = 0; i < 27; i++) //using loop for the search
	  {
	    if (arrNames[i] == ndriverName)
		{
          index = i;
          result = arrNames[index].toUpperCase() + ' is from ' + arrCountry[index].toUpperCase()
          + ' About him:- \n' + arrInfo[index];
          imgDriver = arrImgs[index];		  
		}
	  }
	  
	  if (index == -1)  
	  {
		result = "Driver currently does not exist in database! Please try again later. We are always adding your favourite drivers.";
		imgDriver = "../img/none.jpg";
	  }
		
		document.getElementById("Res").innerHTML = result;
		document.getElementById("Rimg").src = imgDriver;	  
	}